version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: tuarica
      POSTGRES_PASSWORD: Superman111
      POSTGRES_DB: tuarica_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://tuarica:Superman111@db:5432/tuarica_db
      - ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3001
    ports:
      - "3002:3000"
    depends_on:
      - api

volumes:
  postgres_data:
