import './globals.css';

export const metadata = {
  title: 'TuArica',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/picaflor.png" />
      </head>
      <body>{children}</body>
    </html>
  )
}
