import './globals.css';
import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";
import { usePathname } from "next/navigation";

export const metadata = {
  title: 'TuArica',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // El layout solo contiene encabezado y pie de página

  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/picaflor.png" />
      </head>
      <body>
        <Header titulo="TuArica" />
        {/* El contenido principal se renderiza en cada página */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
